GET http://localhost:3077/api/users/search
content-type: application/json

###
GET http://localhost:3077/api/users/create
content-type: application/json

{
    "firstname": "Example A",
    "lastname": "Example B",
    "description": "Example description"
}

###
GET http://localhost:3077/api/users/update?id=609956a1b5835cf5a3749e18
content-type: application/json

{
    "firstname": "Example D"
}

###
GET http://localhost:3077/api/users/delete?
content-type: application/json